LibertyDSNP/parquetjs

package.json
Setup package.json to support the dist directory instead of just including lib directly
=> Point to dist instead of lib

package-lock.json, tsconfig.json
Broken build. 
The change to bloomFilterReader in [PR #17 ](https://github.com/LibertyDSNP/parquetjs/pull/17) undid a side-effect:  because it imported `ParquetEnvelopeReader` from `"parquet"`, tsc was dutifully copying the parquet.js file to the dist folder.  After it was imported via relative path (`"../reader"`), the side-effect went away and parquet.js was no longer copied and so no longer published with the package, which breaks it.
Add parquet.js explicitly to the "include" list in tsconfig.
Also regenerated package-lock.json to bump some patch versions.
1. Check out the sdk
1. Check out this branch
1. alter .tool-versions to use the same as what is in the sdk
1. run `npm i && npm link`
1. go to the sdk repo and run `npm link @dsnp/parquetjs`
1. All tests should pass, but …
=> fix bug caused by side-effect of change in bloomFilterReader. regen package-lock

lib/bloom/sbbf.ts, lib/codec/plain.js, lib/types.js, package-lock.json, package.json
Fixes to small issues found while making this work in-browser.
* Update bson package from 2.0.8 to 4.4.0 due to a vulnerability in v2.  The interface changed, so update the files that use the package.
* Remove an unused TypeArray import.
* Remove a stray comment.
CI should be passing.
=> update BSON due to vulnerability, minor changes

esbuild.js
In some packages we may need a common.js or ESM build as well as the default IIFC build.
This PR adds those build targets.
=> add cjs and ejm builds

lib/bufferReader.ts, lib/codec/index.js, lib/codec/index.ts, lib/codec/plain.ts, lib/codec/plain_dictionary.ts, lib/codec/rle.ts, lib/codec/types.ts, lib/compression.ts, lib/custom.d.ts, lib/types.ts, package-lock.json, package.json, test/codec_plain.test.js, test/codec_rle.js, test/types.js, test/types.ts, tsconfig.json
Problem
=======
[Github Issues #27 ] 
========
Converted the files listed in the issues into typescript without using any
- Each file is changed to typescript 
Running all the tests should still work
=> Chore/typescript conversion/27

lib/bloomFilterIO/bloomFilterReader.ts, package-lock.json, package.json, test/sbbf.ts
Problem
=======
[Github Issue #30 ]
We want to update esbuild and typescript to later versions
Solution
========
I ran `npm install typescript@latest` and `npm install esbuild@latest`
* Ran updates
* Fixed new typescript issue where caught errors are seen as unknown
1.  All tests run
2. Building with esbuild still works
=> updated typescript and esbuild. Fixed typescript issue

lib/util.ts
This may not be necessary, since we have upgraded Thrift to a version above 0.9.2.
See https://github.com/apache/thrift/blob/master/CHANGES.md\#092
Problem
=======
Since upgrading to Thrift ^0.92, we no longer need to patch the TFramedTransport class. However, since the Thrift type definitions don't expose a def for `readPos` (despite exposing a class that implements that field), we still need a patch that defines an attribute for it.
Solution
=======
Since we need to use a `readPos` attribute in our readers, I've slimmed down the patch class to have the attributes we depend on.
=> [Issue #41] - Slimmed down FixedTFramedTransport class

lib/util.ts, parquet.js
Problem
=======
We currently have a function force32 that forces 64bit numbers into 32bit. This is dangerous because we want parquetjs to handle 64 bit numbers. We should look into removing this function.
issue https://github.com/LibertyDSNP/parquetjs/issues/43
* removed force32
Notes
I did not find any usages in SDK or any other repositories.
=> removed force32

lib/util.ts
Problem
=======
The purpose of this PR is to remove the places where we mutate `PageLocation`'s prototype. Since the `PageLocation` type definition does not declare a `read` or `write` member, we were forced to `@ts-ignore` it.
Solution
========
It seems like the `offset`, `compressed_page_size` and `first_row_index` members are explicitly declared on the type definitions. So to satisfy the original author's interface def, I've left the lines of code where we define these members on our PageLocation instance. If this is a bad idea, please comment.
=> [Issue-42]: Remove TS Ignored lines from Util.ts

lib/reader.ts, test/reader.js
Problem
=======
Cursors are a pain to deal with. `for await` is easier for many iteration needs.
Solution
========
Added `Symbol.asyncIterator` to `ParquetReader`.
Closes: #53
1. Test should run
```javascript
const reader = await parquet.ParquetReader.openFile('test.parquet', {});
for await (const record of reader) {
console.log(record);
}
await reader.close();
```
=> Support async iteration in the reader

lib/bufferReader.ts
Problem
=======
This PR removes the async keyword from the `BufferReader.read` method.
Closes #45
=> Removed async keyword from BufferReader.read

lib/reader.ts
Pull in performance improvement for large row counts.
Closes: #56 
I tested this first with 100x run of with fruits.parquet (40,000 rows) and at least with Node 14+ and Node 16+ it is faster with the `shift` version by ~3% (old: ~15s, new ~15.5s).
Then I tried again (1x run) with a file that was 7,667,792 rows (https://ursa-labs-taxi-data.s3.us-east-2.amazonaws.com/2019/01/data.parquet):
shift: ~190s
cursor: ~34s
Major difference.
=> Performance improvements using a cursor instead of a shift

lib/types.ts
Problem
=======
TIMESTAMP_MICROS would not always handle bigint correctly.
From: https://github.com/ZJONSSON/parquetjs/issues/58
Solution
========
Cleanup the code some
* Fix up TIMESTAMP_MICROS functions
* Fix toPrimitive_TIME_MILLIS to better handle overflows.
=> Better handling of millis and micros

lib/schema.ts, test/schema.js
Problem
=======
This PR is intended to implement 2 enhancements to schema error reporting.
* When a parquet schema includes an invalid type, encoding or compression the current error does not indicate which column has the the problem
* When a parquet schema has multiple issues, the code currently fails on the first, making multiple errors quite cumbersome
Solution
========
Modified the schema.ts and added tests to:
* Change error messages from the original `invalid parquet type: UNKNOWN` to `invalid parquet type: UNKNOWN, for Column: quantity`
* Keep track of schema errors as we loop through each column in the schema, and at the end, if there are any errors report them all as below:
`invalid parquet type: UNKNOWN, for Column: quantity`
`invalid parquet type: UNKNOWN, for Column: value` …
=> Feature - collect and report multiple field errors

lib/codec/plain.ts, lib/codec/plain_dictionary.ts, lib/codec/rle.ts, lib/codec/types.ts, lib/reader.ts, lib/schema.ts, lib/writer.ts, package-lock.json, test/integration.js, test/schema.js
Problem
=======
Need to support writing decimal types
Also closes: #87 
Solution
========
Add basic encoding support for decimals
* Added better decimal field errors
* Default scale to 0 per spec
* Cleanup types on RLE so it only asks for what is needed
* Support decimal encoding
* Add test for write / read of decimal
1. Generate a schema with decimal field
2. Use it!
=> Decimal Writer Support

lib/writer.ts, test/statistics.js
Problem
=======
Parquet file column indexes are required to have `null_pages` and `boundary_order`, but they were missing from Parquetjs generated files.
https://github.com/apache/parquet-format/blob/1603152f8991809e8ad29659dffa224b4284f31b/src/main/thrift/parquet.thrift#L955
Closes #92 
Solution
========
Note: While required, the requirement is not always a hard requirement depending on the library.
1. Checkout the branch 
2. `npm i && npm run build && npm pack `
3. Install parquet cli tools (macOS brew: `brew install parquet-cli`)
4. Checkout the bug repo from #92 https://github.com/noxify/parquetjs_bug/
5. `cd parquetjs_bug/parquetjs && npm i`
6. `node index.js && parquet column-index ../generated_files/parquetjs/change.parque` will FAIL
7. npm i …
=> Add null pages and boundary order (Fixes #92)

README.md, test/readme-examples.test.ts
Problem
=======
Docs were wrong from a long time ago per https://github.com/ironSource/parquetjs/issues/100
Solution
========
Updated the docs and added a simple test
Closes #106
=> Update docs and add simple test for readme encoding examples

esbuild-serve.js, examples/server/README.md, lib/bufferReader.ts, lib/codec/plain.ts, lib/codec/plain_dictionary.ts, lib/reader.ts, test/bloomFilterIntegration.ts, test/integration.js, test/lib/bufferReader.test.js
- Buffer.slice -> Buffer.subarray (and correct test that wasn't using buffers)
- new Buffer(array) -> Buffer.from(array)
- Fix issue with `npm run serve`
Via looking into #117 As `subarray` is slightly faster in the browser shim.
=> Update Deprecated Function Calls

lib/compression.ts, package-lock.json, package.json
Per @ MaTiAtSIE via https://github.com/LibertyDSNP/parquetjs/issues/120#issuecomment-1997057706
Switch from the older, non-maintained [wasm-brotli](https://github.com/dfrankland/wasm-brotli) to the newer and maintained [brotli-wasm](https://github.com/httptoolkit/brotli-wasm).
Drop in swap, all tests still pass.
Closes #120
=> Swap brotli dependency

lib/reader.ts, test/reference-test/first-record.ts, test/reference-test/read-all.test.ts, test/test-files.js
As reported in #121 and #131 there are issues with the parsing of `FIXED_LEN_BYTE_ARRAY` values. This may be caused by the fact that they are converted to strings as part of the decoding process for DICTIONARY_PAGE types. This should close both issues.
Solution
========
By removing the `toString` conversion this removes the error, and byte array values get returned as Buffers, as well as also returning numeric types as numbers, and not as strings.
To try to check that the change would only impact things as expected, I also added some regression testing for all of the reference files. For this I've added a check for the first record returned by each reference file. The process to get this data was to add the test, see the error message and then fix the test. 
With this regression in place, …
=> Remove to string for dictionary pages

package-lock.json, package.json
- Previous version of zenfs-core had an engine requirement of >=22 which was higher than the engine requirement for this library (18.18.2) which caused issues with installing the library using yarn. (Yarn seemed to error on engine mismatch but trying it with npm just seemed to log a warning)
In release 1.8.0 the browserfs dependency was replaced with zenfs (#134). This ^0.14.0 version has a engine requirement of 22, which has caused issues when I've tried to install this package in a node 18 project. The engine requirement for this library is 18.18.2.
Solution
========
In the 0.15.1 release of `@zenfs/core` they've added a polyfill and reduced the engine requirement to node 16. https://github.com/zen-fs/core/releases/tag/v0.15.1
I've bumped the version all the way to ^0.16.0 in case there …
=> Bump version of @zenfs/core to ^0.16.0

lib/bufferReader.ts, lib/codec/plain.ts, lib/codec/types.ts, lib/declare.ts, lib/reader.ts, test/int96_timestamp.test.js
There's currently no way to handle INT96 timestamps.
Closes #158
Solution
========
add a flag to enable treating all INT96 fields in a file as timestamps.
```
const reader = await ParquetReader.openFile('your-file.parquet', { 
treatInt96AsTimestamp: true 
})
```
`npm test -- -g "INT96 timestamp handling"`
```bash
INT96 timestamp handling
✔ should handle INT96 values as numbers by default (4593ms)
block_timestamp timestamp: 2016-05-22T08:22:02.000Z
last_modified timestamp: 2022-09-12T01:05:04.629Z
✔ should convert INT96 values to timestamps when option is enabled (3125ms)
```
=> add capability and option flag to treat int96 as a timestamp
